### ISSUE TITLE
Epic: Operator v1.0 Tracker

### ISSUE THREAD

**Issue by schristoff** [getporter/operator#236]
We have Github Boards at the org level, which is great, but it can be difficult to capture conversations in there. 
Operator v1.0 is scheduled for **code freeze September 27th**, with a release of **September 30th**. 

The board for tracking [v1.0 is here](https://github.com/orgs/getporter/projects/3)

The items without issues should have issues made, but I just haven't gotten around to it **yet**

Code 👩‍💻

- [x] [Porter fails auth for installation image pull with Kubernetes driver
](https://github.com/getporter/porter/issues/2339)
- [x] #63 
- [x] #54 
    - [x] #134  (depends on #54)
- [x]  #32 

Docs ✍️

- [x] Create demos section - user created demos welcome! #210  (We currently are seeking demos for GKE/AWS and anything else!)
- [x] Update Documentation, especially getting started #261 
- [x]  Blog for release of v1.0
- [ ] Matrix for clouds and stuff we support (update!)

**Comment by troy0820** [comment]
For https://github.com/getporter/operator/issues/63

I know we use the porter cli as a "agent" to surface the outputs from the output of the cli.  
Questions around this issue: 

1. Are we creating a GRPC service to expose this where we still have to do this (the porter cli)?
1. Are we also creating a CRD to have that be a thing?   
2. Are all outputs created equal? 
3. What outputs do we want? Paramsets, etc 
4. A lot of things are stored in state by the mongodb database and are we running that along side of the porter operator to capture this? 
5. Each job that creates the porter cli invocation has to run the mongodb driver (or whatever backend it needs) to achieve the state of updating, etc porter bundles, do we want to offload this to etcd as the source of truth? 

_(I may edit these questions as more things come to mind)_
